apiVersion: v2
appVersion: v1.1.0
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  version: 1.x.x
description: A Helm chart for karmada
kubeVersion: '>= 1.16.0-0'
maintainers:
- email: jrkeen@hotmail.com
  name: jrkeen
- email: jackson.cloudnative@gmail.com
  name: pidb
name: karmada
type: application
version: 0.0.5
